name: my_rating_app_mobile
description: "Mobile App to manage players ratings"


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.5
  firebase_auth: ^4.17.6
  google_sign_in: ^6.2.1
  flutter_svg: ^2.0.5
  interval_time_picker: ^2.0.0+5
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - lib/icons/