// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVBPkiP6jQu_w8HxOnaRU-RHr33WCEehA',
    appId: '1:387624651112:web:24c650c3231f9ac4996edd',
    messagingSenderId: '387624651112',
    projectId: 'my-rating-app-auth',
    authDomain: 'my-rating-app-auth.firebaseapp.com',
    storageBucket: 'my-rating-app-auth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEcxmdcBWLzDlnN-jzd7ORXrx0StiDRN4',
    appId: '1:387624651112:android:cefda9cd70345e99996edd',
    messagingSenderId: '387624651112',
    projectId: 'my-rating-app-auth',
    storageBucket: 'my-rating-app-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAGipl2cdc58Pc0BEIDx75ofj7XNAG4vM',
    appId: '1:387624651112:ios:3e77da921f66fa3d996edd',
    messagingSenderId: '387624651112',
    projectId: 'my-rating-app-auth',
    storageBucket: 'my-rating-app-auth.appspot.com',
    iosBundleId: 'com.turminaz.myRatingAppMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAGipl2cdc58Pc0BEIDx75ofj7XNAG4vM',
    appId: '1:387624651112:ios:fa22dad18d52b687996edd',
    messagingSenderId: '387624651112',
    projectId: 'my-rating-app-auth',
    storageBucket: 'my-rating-app-auth.appspot.com',
    iosBundleId: 'com.turminaz.myRatingAppMobile.RunnerTests',
  );
}
